In [ ]:
import os
import numpy as np
import tensorflow as tf
import tensorflow_datasets as tfds
from tensorflow import keras
from tensorflow.keras import layers
from sklearn import preprocessing
from keras.utils.np_utils import to_categorical

import warnings
warnings.filterwarnings("ignore")

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

In [ ]:
train_dataset = np.load('train_dataset_5k_60.npz')
val_dataset = np.load('validation_dataset_5k_40.npz')
test_dataset = np.load('test_dataset.npz')

# =========== Loading Datasets ===============


x_train = train_dataset['x'].reshape(3000, 784).astype("float32") / 255
y_train = train_dataset['y'].astype("float32")
  
x_val = val_dataset['x'].reshape(2000, 784).astype("float32") / 255
y_val = val_dataset['y'].astype("float32")   
                    
x_test = test_dataset['x'].reshape(10010, 784).astype("float32") / 255
y_test = test_dataset['y'].astype("float32")                    


x_train.shape, y_train.shape, x_val.shape, y_val.shape, x_test.shape, y_test.shape 

((3000, 784), (3000,), (2000, 784), (2000,), (10010, 784), (10010,))

In [ ]:
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(784,)),
    tf.keras.layers.Dense(100, activation='relu'),
    tf.keras.layers.Dense(10)    # didn't use softmax since it will be called when (logits=true) in below step
])
loss_fn = keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
@tf.function
def loss(w1,w2,lamda,loss_fn,y_train,logits): # Lambda
    total_loss = loss_fn(y_train,logits)
    return total_loss + tf.math.exp(lamda)*(tf.nn.l2_loss(w1)+tf.nn.l2_loss(w2))/(2*y_train.shape[0])


#### $\phi(\lambda) = min\{l(w;S^T) + \exp{\lambda}(\|w\|_2^2)\}$ for given $\lambda$

In [ ]:
wt_layer1_init = model.layers[1].get_weights()
wt_layer2_init = model.layers[2].get_weights()

train_df = tf.data.Dataset.from_tensor_slices((x_train,y_train))
train_df = train_df.shuffle(buffer_size = 3000).batch(64)

def fmin_loss(lamda, epochs= 50, l_rate= 0.6, momentum= 0.01, t_hold = 1e-6, nesterov = True):      # lamda, not exp(lamda), Works with both tf.Variable and tf.constant type lambda input, (or just scalar)
    tf.keras.backend.clear_session()
    optimizer = keras.optimizers.SGD(learning_rate=l_rate,momentum = momentum , nesterov =nesterov )
    total_loss0 = 1e20

    for epoch in range(epochs):
        for step,(x_train,y_train) in enumerate(train_df):
            with tf.GradientTape() as tape:
                logits = model(x_train, training=True)
                w1 = model.layers[1].weights[0]
                w2 = model.layers[2].weights[0]
                total_loss1 = loss(w1,w2,lamda,loss_fn,y_train,logits)
                
            vars_list = model.trainable_weights
            grads = tape.gradient(total_loss1, vars_list)      # for ref  - https://www.tensorflow.org/tutorials/customization/custom_training_walkthrough 
            optimizer.apply_gradients(zip(grads,vars_list))

        # if abs( total_loss1-total_loss0 ) <= t_hold:
        #     break
        total_loss0 = total_loss1

    wt_layer1 = model.layers[1].get_weights()
    wt_layer2 = model.layers[2].get_weights()
    model.layers[1].set_weights(wt_layer1_init)
    model.layers[2].set_weights(wt_layer2_init)

    return [total_loss1, wt_layer1, wt_layer2]

In [ ]:
def f_val(w1,b1,w2,b2,lamda): # lamda -> Variable
    layer1_weights = [w1,b1]
    layer2_weights = [w2,b2]
    model.layers[1].set_weights(layer1_weights)
    model.layers[2].set_weights(layer2_weights)
    logits = model(x_train)
    return loss(w1,w2,lamda,loss_fn,y_train,logits)

def f_grad(w1,b1,w2,b2,lamda): # lamda -> Variable
    with tf.GradientTape() as tape:
        total_loss = f_val(w1,b1,w2,b2,lamda)
    vars_list = model.trainable_weights
    vars_list.append(lamda)
    grads = tape.gradient(total_loss, vars_list) 
    return grads

def F_val(w1,b1,w2,b2):     
    layer1_weights = [w1,b1]
    layer2_weights = [w2,b2]
    model.layers[1].set_weights(layer1_weights)
    model.layers[2].set_weights(layer2_weights)
    logits = model(x_val)
    return loss_fn(y_val,logits)

def F_grad(w1,b1,w2,b2):   # float32 arrays
    with tf.GradientTape() as tape:
        total_loss = F_val(w1,b1,w2,b2)
    vars_list = model.trainable_weights
    grads = tape.gradient(total_loss, vars_list) 
    return grads

### Gaussian Process Regressor

In [ ]:
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF
import matplotlib.pyplot as plt

def GPR( Lamda_sample, Phi_sample, lamda ):

    kernel = 1 * RBF(length_scale=1.0, length_scale_bounds=(1e-4, 1e4))
    gaussian_process = GaussianProcessRegressor(kernel=kernel, n_restarts_optimizer=9)
    gaussian_process.fit(Lamda_sample, Phi_sample)

    k2_l = gaussian_process.kernel_.get_params()['k2__length_scale']
    x = lamda
    y_pred, sigma = gaussian_process.predict(x, return_std=True)
    y_pred_grad = 0.0*y_pred

    for key, x_star in enumerate(x):

        k_val=gaussian_process.kernel_( Lamda_sample , np.atleast_2d(x_star) , eval_gradient=False).ravel() 
        x_diff_over_l_sq = ((Lamda_sample-x_star)/np.power(k2_l,2)).ravel()
        intermediate_result = np.multiply(k_val, x_diff_over_l_sq)
        final_result = np.dot(intermediate_result, gaussian_process.alpha_)
        y_pred_grad[key] = final_result
        
    return [y_pred[0], y_pred_grad[0]]

In [ ]:
def Function_Grad( w1,b1,w2,b2,lamda, Lamda_sample, Phi_sample, R_val, Mu_val ):

    Phi = GPR(Lamda_sample, Phi_sample, np.array([[lamda.numpy()[0]]]))
    Phi_val, Phi_grad = Phi[0], Phi[1]
    
    p1 = F_grad( w1,b1,w2,b2 ) 
    p2 = ( R_val* ( f_val(w1,b1,w2,b2,lamda) -  Phi_val) + Mu_val )
    f_gradient = f_grad(w1,b1,w2,b2,lamda)
    p3 = f_gradient[:-1] + [f_gradient[-1]-Phi_grad]
    p2tp3 = [p2*elt for elt in p3]

    gradients = [e1+e2 for e1,e2 in zip(p1,p2tp3[:-1])] + [p2tp3[-1]]
    gradients = [(tf.clip_by_norm(grad, clip_norm = 2.0)) for grad in gradients]

    return gradients   # Output : w1, b1, w2, b2, lamda : floar32 arrays

In [ ]:
def AugLag_Function( w1,b1,w2,b2,lamda, Lamda_sample, Phi_sample, R_val, Mu_val ):
    PHI = GPR(Lamda_sample, Phi_sample, np.array([[lamda.numpy()[0]]]))
    f_phi = f_val(w1,b1,w2,b2,lamda) - PHI[0]
    final_val = F_val(w1,b1,w2,b2) + (R_val/2) * f_phi**2 + Mu_val * f_phi
    return final_val.numpy()[0]

In [ ]:
def Gradient_Descent( w1,b1,w2,b2,lamda,Lamda_sample, Phi_sample, R_val, Mu_val, momentum, learning_rate, 
                     epochs = 80, Opt_tol = 1e-10, F_tol = 1e-6 ): # With Nesterov Momentum

    w1_update0 = np.zeros((784,100),dtype='float32')
    b1_update0 = np.zeros((100),dtype='float32')
    w2_update0 = np.zeros((100,10),dtype='float32')
    b2_update0 = np.zeros((10),dtype='float32')
    lamda_update0 = np.zeros((1),dtype='float32')

    w1_weight0, w2_weight0, b1_weight0, b2_weight0, lamda_weight0 = w1, w2, b1, b2, lamda  # Initialized weights
    Loss_val = 1e+20
    #Z_VAL0 = 1e+20
    Opt_weights = []
    
    for epoch in range(epochs):

        w1_weight_ahead = w1_weight0 - momentum*w1_update0
        b1_weight_ahead = b1_weight0 - momentum*b1_update0
        w2_weight_ahead = w2_weight0 - momentum*w2_update0
        b2_weight_ahead = b2_weight0 - momentum*b2_update0

        lamda_weight_ahead = lamda_weight0 - momentum*lamda_update0
        lamda_weight_ahead = tf.Variable(lamda_weight_ahead.numpy(), dtype = tf.float32)

        Grad_list = Function_Grad( w1_weight_ahead, b1_weight_ahead, w2_weight_ahead, b2_weight_ahead, 
                                  lamda_weight_ahead, Lamda_sample, Phi_sample, R_val, Mu_val )

        learning_rate = tf.constant(learning_rate, dtype=tf.float32)
        momentum = tf.constant(momentum, dtype=tf.float32)

        part1 = [momentum*update for update in [w1_update0, b1_update0, w2_update0, b2_update0, lamda_update0]]
        part2 = [learning_rate * grad for grad in Grad_list]

        [w1_update0, b1_update0, w2_update0, b2_update0, lamda_update0] = [i+j for i,j in zip(part1,part2)]  
        [w1_weight0, b1_weight0, w2_weight0, b2_weight0, lamda_weight0] = np.subtract([w1_weight0, b1_weight0, w2_weight0, b2_weight0, lamda_weight0], 
                                                                                      [w1_update0, b1_update0, w2_update0, b2_update0, lamda_update0])
        
        Z_VAL = AugLag_Function( w1_weight0, b1_weight0, w2_weight0, b2_weight0, lamda_weight0,
                                Lamda_sample, Phi_sample, R_val, Mu_val )
        Optimality_Tolerance = np.array([np.linalg.norm( optgd, ord = np.inf ) for optgd in Grad_list])

        if Z_VAL <= Loss_val :
            
            Opt_weights = [w1_weight0, b1_weight0, w2_weight0, b2_weight0, lamda_weight0]
            fun_tol = abs( (Z_VAL-Loss_val)/(1+abs(Loss_val)) )
            
            if  fun_tol <= F_tol and np.all(Optimality_Tolerance) <= Opt_tol:
                Loss_val = Z_VAL
                break
                
            Loss_val = Z_VAL
        #=====================================================================================

    return Opt_weights, Loss_val   # w1, b1, w2, b2, lamda


In [ ]:
def LOSS_FUNCTION( wts1, wts2 ):
  
  model.layers[1].set_weights(wts1)
  model.layers[2].set_weights(wts2)

  val_logits = model(x_val)
  val_loss = loss_fn(y_val,val_logits)

  train_logits = model(x_train)
  training_loss = loss_fn(y_train,train_logits)

  test_logits = model(x_test)
  test_loss = loss_fn(y_test,test_logits)

  return val_loss, training_loss, test_loss

In [ ]:
# GLOBAL : Lamda_sample, Phi_sample
def Augmented_Lagrangian( w1,b1,w2,b2,lamda, Lamda_sample, Phi_sample, mom, lr, R_val = 2,
                         Mu_val = 2, neta = 1.5, al_epochs = 5 ):
    Z_val0 = 1e+20
    wts_opt0, lamda_opt0, min_violation = [], 0, 10
    for epoch in range(al_epochs):

        Opt_Weights, _ = Gradient_Descent( w1,b1,w2,b2,lamda, Lamda_sample, Phi_sample, R_val, Mu_val, mom, lr)
        
        w1_opt,b1_opt,w2_opt,b2_opt,lamda_opt = Opt_Weights[0], Opt_Weights[1], Opt_Weights[2], Opt_Weights[3], Opt_Weights[4]  # lamda not var
        
        valL, trL, testL = LOSS_FUNCTION( [w1_opt,b1_opt], [w2_opt,b2_opt] )

        # ========== Setting Weights for Next Loop ====================
        #w1,b1,w2,b2,lamda = w1_opt,b1_opt,w2_opt,b2_opt,lamda_opt
        
        # ============== Updating Augmented Lagrangian Parameters ====================
        Phi1 = GPR(Lamda_sample, Phi_sample, np.array([[lamda_opt.numpy()[0]]]))
        Phi_val1 = Phi1[0]
        lamda_opt = tf.Variable(lamda_opt, dtype=tf.float32)                   # Converting lamda to var
        constraint_ = f_val(w1_opt,b1_opt,w2_opt,b2_opt,lamda_opt) - Phi_val1
        Mu_val = Mu_val + R_val*( constraint_ )
        R_val  = neta*R_val

        # ===== Constraint Violation Criteria ===================
        violation = abs(constraint_)
        print("\n\n Violation = ", violation,"Lambda = ", lamda_opt.numpy()[0], f" Train_Loss : {trL}, Val_Loss : {valL}, Test_Loss : {testL}")
        # if violation <= min_violation:
        wts_opt0 = [ [w1_opt, b1_opt], [w2_opt, b2_opt]]
        #   lamda_opt0 = lamda_opt
        #   min_violation = violation
        
        # ==========UPDATING LAMBDA SAMPLE FOR GPR=========================
        Lamda_sample = np.sort(np.array(np.vstack([Lamda_sample,[lamda_opt.numpy()]]), dtype = 'float32'), axis = 0)
        index = np.where(Lamda_sample == [lamda_opt.numpy()[0]] )
        Phi_new_lamda = fmin_loss(lamda_opt)[0].numpy()[0]
        Phi_sample = np.insert(Phi_sample, index[0][0], Phi_new_lamda)
      
    print(f"\n Optimal Lambda = {lamda_opt.numpy()[0]}")
    return wts_opt0, lamda_opt #, min_violation

In [ ]:
Lamda_sample = np.arange(-10,0,1, dtype = 'float32').reshape((-1,1))

Phi_sample, Weights, lamda_init = [], [], 0
init_val_loss = 1e20
for lamda in Lamda_sample:
    
    [min_loss, layer1wt, layer2wt] = fmin_loss(lamda)
    Phi_sample.append( min_loss.numpy()[0] )
    
    model.layers[1].set_weights(layer1wt)
    model.layers[2].set_weights(layer2wt)
    val_logits = model(x_val)
    val_loss = loss_fn(y_val,val_logits)
    if val_loss <= init_val_loss :
        init_val_loss = val_loss
        Weights = [layer1wt, layer2wt]
        lamda_init = lamda
        
Phi_sample = np.array(Phi_sample)
print("\n\n Phi_sample: ", Phi_sample, "\n\n")

#============================== Initializing Weights =================================================
# w1, b1 = Weights[0][0], Weights[0][1]
# w2, b2 = Weights[1][0], Weights[1][1]
# lamda = tf.Variable(lamda_init, dtype = tf.float32)




 Phi_sample:  [0.001465   0.00075194 0.00118724 0.00223559 0.00560613 0.01316278
 0.02719149 0.0542752  0.1090351  0.23284437] 




### Tuning Gradient Descent

In [ ]:
# learn_rate = np.arange( 0.1, 1, 0.1, dtype = 'float32' )
# momentum_set = np.arange( 0.01, 0.1, 0.01 )
learn_rate = np.array( [0.001, 0.01, 0.05, 0.07, 0.1], dtype = 'float32' )
momentum_set = np.array( [0.1, 0.5, 0.8, 0.9, 0.99] )

opt_val = 1e20
l0,m0 = 0,0
for lr in learn_rate:
    for mom in momentum_set:
        w1, b1 = Weights[0][0], Weights[0][1]
        w2, b2 = Weights[1][0], Weights[1][1]
        lamda = tf.Variable(lamda_init, dtype = tf.float32)

        wt, val = Gradient_Descent( w1,b1,w2,b2,lamda,Lamda_sample, Phi_sample, R_val = 2, Mu_val = 2,
                                   momentum = mom, learning_rate = lr )
        print("\n LR : {}, MOM : {}, Z_VAL : {}".format(lr,mom,val))
        
        if val <= opt_val:
            opt_val = val
            l0,m0 = lr,mom
print("\n\n Optimum : ",  opt_val, " Momentum : {}, LR : {}".format(m0,l0))


 LR : 0.0010000000474974513, MOM : 0.1, Z_VAL : 0.09269604086875916

 LR : 0.0010000000474974513, MOM : 0.5, Z_VAL : 0.08027750253677368

 LR : 0.0010000000474974513, MOM : 0.8, Z_VAL : 0.04953892529010773

 LR : 0.0010000000474974513, MOM : 0.9, Z_VAL : 0.003701522946357727

 LR : 0.0010000000474974513, MOM : 0.99, Z_VAL : -0.6227986216545105

 LR : 0.009999999776482582, MOM : 0.1, Z_VAL : -0.012344911694526672

 LR : 0.009999999776482582, MOM : 0.5, Z_VAL : -0.11443436145782471

 LR : 0.009999999776482582, MOM : 0.8, Z_VAL : -0.6037972569465637

 LR : 0.009999999776482582, MOM : 0.9, Z_VAL : -0.8731462955474854

 LR : 0.009999999776482582, MOM : 0.99, Z_VAL : -0.9879288077354431

 LR : 0.05000000074505806, MOM : 0.1, Z_VAL : -0.7142205834388733

 LR : 0.05000000074505806, MOM : 0.5, Z_VAL : -0.8715137243270874

 LR : 0.05000000074505806, MOM : 0.8, Z_VAL : -0.9306536316871643

 LR : 0.05000000074505806, MOM : 0.9, Z_VAL : -0.9566768407821655

 LR : 0.05000000074505806, MOM : 0.99, Z

## LLO = 10 (+5)

###### Note : The result might differ a little because of GPR estimation every time the program is executed. Training the program to its optimal is avoided because it fits the model over training and validation dataset too well, leading to overfitting on validation dataset. 

In [ ]:
# ===========FINDING LOSS=======================

w1, b1 = Weights[0][0], Weights[0][1]
w2, b2 = Weights[1][0], Weights[1][1]
lamda = tf.Variable(lamda_init, dtype = tf.float32)

wt_final, lamda_final = Augmented_Lagrangian( w1, b1, w2, b2, lamda, Lamda_sample, Phi_sample, m0, l0 )

Final_weights_1, Final_weights_2 = wt_final[0], wt_final[1]
val_loss, training_loss, test_loss = LOSS_FUNCTION(Final_weights_1,Final_weights_2 )

print(f'Validation Loss : {val_loss}, Training Loss : {training_loss}, Testing Loss : {test_loss}')



 Violation =  tf.Tensor([0.5033908], shape=(1,), dtype=float32) Lambda =  1.0961769  Train_Loss : 0.012343702837824821, Val_Loss : 0.009152368642389774, Test_Loss : 0.23267892003059387


 Violation =  tf.Tensor([0.321246], shape=(1,), dtype=float32) Lambda =  -0.1448857  Train_Loss : 0.11168576776981354, Val_Loss : 0.014085515402257442, Test_Loss : 0.26525402069091797


 Violation =  tf.Tensor([0.02682782], shape=(1,), dtype=float32) Lambda =  -2.8429246  Train_Loss : 0.08575254678726196, Val_Loss : 0.014549980871379375, Test_Loss : 0.25131815671920776


 Violation =  tf.Tensor([0.00323461], shape=(1,), dtype=float32) Lambda =  -3.279241  Train_Loss : 0.06032222509384155, Val_Loss : 0.013646169565618038, Test_Loss : 0.24216175079345703


 Violation =  tf.Tensor([0.0017165], shape=(1,), dtype=float32) Lambda =  -2.7528846  Train_Loss : 0.04832477495074272, Val_Loss : 0.013327003456652164, Test_Loss : 0.23835283517837524

 Optimal Lambda = -2.75288462638855
Validation Loss : 0.01332700

## RUN 2

In [ ]:
# ===========FINDING LOSS=======================

w1, b1 = Weights[0][0], Weights[0][1]
w2, b2 = Weights[1][0], Weights[1][1]
lamda = tf.Variable(lamda_init, dtype = tf.float32)

wt_final, lamda_final = Augmented_Lagrangian( w1, b1, w2, b2, lamda, Lamda_sample, Phi_sample, m0, l0 )

Final_weights_1, Final_weights_2 = wt_final[0], wt_final[1]
val_loss, training_loss, test_loss = LOSS_FUNCTION(Final_weights_1,Final_weights_2 )

print(f'Validation Loss : {val_loss}, Training Loss : {training_loss}, Testing Loss : {test_loss}')



 Violation =  tf.Tensor([0.5031711], shape=(1,), dtype=float32) Lambda =  1.0691944  Train_Loss : 0.012894687242805958, Val_Loss : 0.009143189527094364, Test_Loss : 0.2330009788274765


 Violation =  tf.Tensor([0.2709697], shape=(1,), dtype=float32) Lambda =  -0.04971412  Train_Loss : 0.1630280315876007, Val_Loss : 0.016089271754026413, Test_Loss : 0.291731059551239


 Violation =  tf.Tensor([0.02196291], shape=(1,), dtype=float32) Lambda =  -2.0303788  Train_Loss : 0.08207900822162628, Val_Loss : 0.014001564122736454, Test_Loss : 0.250826895236969


 Violation =  tf.Tensor([0.01223473], shape=(1,), dtype=float32) Lambda =  -3.7565382  Train_Loss : 0.07040217518806458, Val_Loss : 0.013373413123190403, Test_Loss : 0.2454884648323059


 Violation =  tf.Tensor([0.00721183], shape=(1,), dtype=float32) Lambda =  -3.5506096  Train_Loss : 0.04117424413561821, Val_Loss : 0.013605846092104912, Test_Loss : 0.2344062179327011

 Optimal Lambda = -3.550609588623047
Validation Loss : 0.01360584609